In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("podcastindex_feeds.db")   # use your extracted file's name

pd.read_sql("PRAGMA table_info(podcasts)", conn)          # columns
pd.read_sql("SELECT * FROM podcasts LIMIT 5", conn).T     # sample rows, transposed so columns are readable
pd.read_sql("""SELECT language, COUNT(*) AS n FROM podcasts
               GROUP BY language ORDER BY n DESC LIMIT 30""", conn)

   language        n
0        en  1866288
1     en-us   512043
2        es   461199
3        pt   189134
4     es-ES   148474
5     en-US   140825
6             115242
7        in   101442
8        fr   100449
9        de    91635
10       it    70856
11    pt-br    62315
12       ja    47172
13    en-gb    42353
14    es-mx    35398
15    zh-cn    34926
16       ru    34635
17       id    32114
18       hi    30564
19       ar    26808
20       zh    25985
21       nl    24287
22       tr    23481
23       pl    18583
24    de-de    15975
25       sv    14890
26    en-au    14716
27  zh-Hant    14180
28       fa    13190
29       da    12547

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 300)

sample = pd.read_sql("SELECT * FROM podcasts WHERE dead = 0 LIMIT 15", conn)
sample.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
id,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16
url,https://markalanwilliams.libsyn.com/rss,https://anchor.fm/s/19ccb320/podcast/rss,https://feeds.soundcloud.com/users/soundcloud:users:150466516/sounds.rss,https://audioboom.com/channels/4597972.rss,https://anchor.fm/s/212c47d4/podcast/rss,http://feeds.feedburner.com/DirtBikePodcast,https://anchor.fm/s/28f184c/podcast/rss,https://galaktacus.libsyn.com/rss,https://sportsfromherperspective.podomatic.com/rss2.xml,https://feeds.soundcloud.com/users/soundcloud:users:37022259/sounds.rss,https://feeds.soundcloud.com/users/soundcloud:users:151205561/sounds.rss,https://nocturniarecords.podomatic.com/rss2.xml,https://feeds.soundcloud.com/users/soundcloud:users:142613909/sounds.rss,https://noextrawords.libsyn.com/rss,http://feeds.feedburner.com/TheSpysonHour
title,Christianity Questions and Answers,Rahdo Talks Through,IdiotSpeakShow,Conciertos en el Living,OriginALL,2017 U.S. Dirt Bike Events,RNG Show,Galaktacus,Sports From Her Perspective,Romos Music,One Way Ticket to Nilbog,TECHNO TALES OF NOCTURNIA,City Talk w/ Rob Rolison,No Extra Words one person's search for story,The Tyson Hour
lastUpdate,1790336823,1786983470,1776023740,1775938543,1776144276,1717655168,1776153885,1776208256,1776983799,1790924645,1776107975,1775648564,1763234781,1775448893,1773736786
link,http://markalanwilliams.libsyn.com/webpage,https://patreon.com/rahdo,https://soundcloud.com/idiotspeakshow,http://conciertosenelliving.com/podcast/,https://originall.citypodcast.ro,http://www.usdualsports.com/feeds/posts/default,https://podcasters.spotify.com/pod/show/rngshow,http://galaktacus.libsyn.com/podcast,https://www.podomatic.com/podcasts/sportsfromherperspective,https://soundcloud.com/romibee,http://onewaytickettonilbog.weebly.com,https://www.podomatic.com/podcasts/nocturniarecords,https://soundcloud.com/robrolison,http://noextrawords.wordpress.com,https://robhasawebsite.com/
lastHttpStatus,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200
dead,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
contentType,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,text/xml; charset=UTF-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,application/xml; charset=utf-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,application/xml; charset=utf-8,application/rss+xml; charset=utf-8,application/rss+xml; charset=utf-8,text/xml; charset=UTF-8
itunesId,1000000618,1000016089,1000035657,1000035702,1000035707,1000044791,1000075223,1000081327,1000083229,1000090525,1000090572,1000093513,1000095128,1000095644,1000101673
originalUrl,https://markalanwilliams.libsyn.com/rss,https://anchor.fm/s/19ccb320/podcast/rss,http://feeds.soundcloud.com/users/soundcloud:users:150466516/sounds.rss,https://audioboom.com/channels/4597972.rss,https://anchor.fm/s/212c47d4/podcast/rss,http://feeds.feedburner.com/DirtBikePodcast,https://anchor.fm/s/28f184c/podcast/rss,https://galaktacus.libsyn.com/rss,http://sportsfromherperspective.podomatic.com/rss2.xml,http://feeds.soundcloud.com/users/soundcloud:users:37022259/sounds.rss,http://feeds.soundcloud.com/users/soundcloud:users:151205561/sounds.rss,http://nocturniarecords.podomatic.com/rss2.xml,http://feeds.soundcloud.com/users/soundcloud:users:142613909/sounds.rss,https://noextrawords.libsyn.com/rss,http://feeds.feedburner.com/TheSpysonHour
itunesAuthor,Dr. Mark Alan Williams,Richard Ham,IdiotSpeakShow,Conciertos en el Living,CityPodcast,Mark Siddons,RNG Media,"Jim Kettner, John Mihaly, and Scott Brown",Sports From Her Perspective,Romos,One Way Ticket to Nilbog,NOCTURNIA RECORDS,Rob Rolison,Kris Baker Dersch,Spencer Pratt & Tyson Apostol make up Spyson
itunesOwnerName,Mark Williams,Richard Ham,IdiotSpeakShow,,CityPodcast,Mark Siddons,RNG Media,Scott Brown,Sports From Her Perspective,Romi Bee,One Way Ticket to Nilbog,,Rob Rolison,Kris Baker Dersch,Spencer Pratt & Tyson Apostol make up Spyson
explicit,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0
imageUrl,https://static.libsyn.com/p/assets/e/7/5/d/e75de19145e2153b/thumb.jpg,https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_nologo/4228456/81316933823cb437.jpeg,https://i1.sndcdn.com/avatars-000143391344-h7vuir-original.png,https://audioboom.com/i/18313196.jpg,https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/5465501/5465501-1618684011189-dc76d23a8863c.jpg,,https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/329323/329323-1540065358182-3c35de8fb1d28.jpg,https://static.libsyn.com/p/assets/7/1/3/8/7138a0d481bf56dd/GalaktacusLogo4Thumb.jpg,https://assets.podomatic.net/ts/e3/d4/66/sportsfromherperspective/3000x3000_10637189.jpg,https://i1.sndcdn.com/avatars-l7EnVkcv05XdBn24-kP2kyg-original.jpg,https://i1.sndcdn.com/avatars-000147882212-cqio1t-original.jpg,https://assets.podomatic.net/ts/df/bb/ee/nocturniarecords/1400x1400_10707556.jpg,https://i1.sndcdn.com/avatars-000147884754-rnc1n6-original.jpg,https://static.libsyn.com/p/assets/8/e/7/2/8e723e1b67b06928/No_Extra_Words_logo_season_2.jpg,https://robhasawebsite.com/wp-content/uploads/powerpress/spyson-rainbo-1400.jpg
itunesType,episodic,episodic,episodic,episodic,episodic,,episodic,episodic,episodic,episodic,episodic,episodic,episodic,episodic,episodic
generator,Libsyn RSSgen 1.0,Anchor Podcasts,,audioboom.com,Anchor Podcasts,Blogger,Anchor Podcasts,Libsyn RSSgen 1.0,Podomatic RSS Generator,,,Podomatic RSS Generator,,Libsyn RSSgen 1.0,https://wordpress.org/?v=6.9.4
newestItemPubdate,1610226815,1716150169,1432935194,1462919594,1663751449,0,1717966429,1516221691,1601347864,1780626748,1462160910,1435834152,1446055795,1595198755,1587536791
language,en,en,en,es,ro,,en,en,en-us,en,en,en-us,en,en,en
oldestItemPubdate,1432837532,1433041200,1432337604,1428532012,1432937220,0,1517097600,1432224000,1432698149,1421672839,1460909679,1433279144,1437491281,1432930316,1572378088
episodeCount,90,464,2,19,49,1,154,98,33,18,2,4,7,152,17
popularityScore,9,9,9,9,9,9,9,9,9,6,6,9,6,9,9
priority,-1,5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
createdOn,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487,1596752487
updateFrequency,9,9,9,9,9,9,9,9,9,7,9,9,9,9,9
chash,cfc6e8dbaacbcba9f0b341c89df9a703,f9fce8424a9918be9182c2d67fc51c16,3414348449422fc0970d059cc680d0ab,2aa375615663506e87f710ec8524afd2,256f22c369b872a5b1f73c8636d21053,05fb7718de54577acaeaa95597d370c7,98b09de08d28f881c3229921b6fdf451,7eb79761fa3855300be5d903068d1d0d,ff4d2891ae07bdba33f3f3684c9f2623,f5e26f4a8084b354236a3e080ad24b95,9393648059ff3edfec369d8b18ee1e09,c646f73ce942f8056cee9b108c4af364,f9e3901b87f3edf5cbfc122e9e0e401b,3a995869a0cd8347480bced3ebda9698,79a230eb0e1e3a8a29429bbf68135187
host,libsyn.com,anchor.fm,soundcloud.com,audioboom.com,anchor.fm,feedburner.com,anchor.fm,libsyn.com,podomatic.com,soundcloud.com,soundcloud.com,podomatic.com,soundcloud.com,libsyn.com,feedburner.com
newestEnclosureUrl,https://traffic.libsyn.com/secure/markalanwilliams/001_Are_all_sins_equal.mp3?dest-id=278964,https://traffic.megaphone.fm/APO8753353300.mp3,https://feeds.soundcloud.com/stream/206778721-idiotspeakshow-idiotspeak-episode-3-game-of-spoilers.mp3,https://dts.podtrac.com/redirect.mp3/audioboom.com/posts/3845502.mp3?modified=1578276820&sid=4597972&source=rss,https://anchor.fm/s/212c47d4/podcast/play/57892884/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2022-8-21%2Fe32288eb-404b-0257-aea7-f76cb3846e1c.mp3,http://ia601505.us.archive.org/4/items/DualSport662015/Dual%20Sport%206-6-2015.mp3,https://anchor.fm/s/28f184c/podcast/play/87819087/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-5-9%2F5fe73e41-2442-a7cf-2286-5b7bda63726e.mp3,https://traffic.libsyn.com/secure/galaktacus/Galaktacus__ZERO.mp3?dest-id=274667,https://sportsfromherperspective.podomatic.com/enclosure/2020-09-28T19_51_04-07_00.mp3,https://feeds.soundcloud.com/stream/2391136464-romibee-born-for-this-wip-1.mp3,http://feeds.soundcloud.com/stream/259531783-onewaytickettonilbog-episode-26-maximum-overdrive.mp3,https://nocturniarecords.podomatic.com/enclosure/2015-06-02T14_05_44-07_00.mp3?_=1433279179.10655259,http://feeds.soundcloud.com/stream/215603180-robrolison-citytalk-7-ready-on-day-one.mp3,https://traffic.libsyn.com/secure/noextrawords/episode_1.mp3?dest-id=276938,https://media.blubrry.com/rob_has_a_podcast_survivor/podone.noxsolutions.com/launchpod/robhasapodcast/mp3/20191029-newsAF211_mixdown_g6qm.mp3
podcastGuid,78e9f51b-0ac3-5711-a921-1f2c7b5dbb35,655b4e1a-4deb-56a2-9256-cad10f099410,7fba92fb-42eb-56da-b562-cef9d2cf2546,7de80904-5ecf-5a91-8818-2d9a02926ccd,fc42afa1-1aa7-52dd-aa49-851ae703a66a,68432d76-bb8d-5d16-9e76-2396c9d52704,6ac4018d-ce57-5468-bb8b-d804699b9371,42786380-17ae-5028-85b5-c9c937ce235b,ec83484f-a8f2-5629-b529-8b664c88767e,9db5033c-3ee9-5491-808d-6815d5baf2bb,76ac165b-665f-5ea4-a212-2083c13ab3e4,6c5b17d8-1ac8-5e6c-88de-09c079e0f71b,3131a4af-176c-5a51-bee3-e9252aa48676,def1b46e-4d9a-54fc-8a6f-e558ba7464cb,b4d73b7f-a618-545c-bfff-7471f665a0b0
description,"Dr. Mark Alan Williams and friends answer questions about the Christian faith: questions about the God, Jesus, the Bible, eternity, belief, religion the reasonableness of faith and others.","A podcast all about boardgames, hosted by Richard ""Rahdo"" Ham",Podcast by IdiotSpeakShow,,"OriginALL este un show cu oameni inteligenți pe care vrei să-i asculți pentru că ei sunt cei care schimbă mentalitatea României. Podcast-ul este realizat, încă din anul 2015, de Adrian Boioglu pentru rețeaua CityPodcast - htpps://www.citypodcast.ro","A site that lists every U.S. Dual Sport Rides, Enduro Rides, Hare Scrambles, Adventure Rides, Dirt Biking, Motocross. You can also find reviews on Dirt Bike products along with dirt bike gear, and products to make your dirt bike street legal.",Every season of Survivor we draft the castaways onto separate teams in a fantasy league and see who among us can form the ultimate team that will outlast the rest. Join us every week as we run through major events from the latest episode and make strategic trades to edge out the competition.,The name Galaktacus originates from a youthful mispronunciation of a classic comic book character best known for eating planets. Before all of the blockbuster film franchises and the non-stop spoiler-filled internet coverage there was limited space to openly discuss such topics let alone their p...,This will be a podcast of sports topics that don't make the show! There's so much going on in the world of sports and just want to touch on all the topics!,Podcast by Romos,"Join Matt, Renee, and Keith on a free ride through B-tier horror films.","NOCTURNIA RECORDS is an independent record label based in Berlin focused on premium dark music.Wait for full moon and new moon nights for new releases, we ve got candy for the black souls of techno. https://soundcloud.com/nocturniarecords","A regular look at all that is happening in Our City, the great city of Poughkeepsie.","A flash fiction podcast featuring short stories less than 2,000 words long.",Pop Culture and Tech News from Spencer Pratt and Tyson Apostol
category1,religion,leisure,,music,business,,tv,tv,sports,music,tv,music,news,arts,tv
category2,spirituality,games,,,careers,,film,film,,,film,,,books,film
category3,christianity,,,,,,reviews,,,,,,,performing,reviews
category4,,,,,,,,,,,,,,,after-shows
category5,,,,,,,,,,,,,,,
category6,,,,,,,,,,,,,,,
category7,,,,,,,,,,,,,,,
category8,,,,,,,,,,,,,,,
category9,,,,,,,,,,,,,,,
category10,,,,,,,,,,,,,,,
newestEnclosureDuration,384,17918,2722,738,2586,,2480,6306,2918,127,1,1964,0,580,1
podcastId,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16
duplicateOf,,,,,,,,,,,,,,,

In [4]:
pd.read_sql("""SELECT category1, COUNT(*) AS n FROM podcasts
               WHERE dead = 0 GROUP BY category1
               ORDER BY n DESC LIMIT 60""", conn)

           category1       n
0            society  787920
1          education  509119
2           business  419229
3               arts  412394
4           religion  398810
5                     286710
6              music  256094
7             health  254897
8             comedy  242575
9               news  240236
10            sports  191897
11           leisure  183759
12                tv  109098
13              kids   87241
14        technology   82378
15           history   73172
16           science   72762
17           fiction   64786
18        government   31577
19        true crime   17711
20             games    9214
21          politics     251
22      christianity     237
23              pets     195
24     entertainment     106
25              food      97
26            social      75
27  self improvement      72
28            travel      71
29           culture      67
30             books      65
31  entrepreneurship      64
32          personal      57
33            places      51
34        philosophy      49
35            family      48
36            mental      46
37          medicine      42
38            visual      39
39        performing      39
40      spirituality      35
41           hobbies      34
42           fantasy      34
43        management      32
44           careers      32
45       alternative      32
46         marketing      29
47            design      27
48        non-profit      26
49          language      26
50              home      25
51        automotive      24
52           natural      23
53         investing      23
54              film      23
55       documentary      23
56           fashion      22
57         sexuality      18
58            nature      18
59       mathematics      17

In [5]:
main_categories = ["technology", "business"]
topic_terms = ["technology", "startup", "fintech", "founder", "entrepreneur",
               "venture capital", "software", "artificial intelligence", "innovation"]

text = "(title || ' ' || IFNULL(description, ''))"
kw_filter = " OR ".join(f"{text} LIKE '%{t}%'" for t in topic_terms)

query = f"""
SELECT id, podcastGuid, title, description, itunesAuthor, language,
       category1, category2, category3, episodeCount, newestItemPubdate, url
FROM podcasts
WHERE dead = 0
  AND language LIKE 'en%'
  AND episodeCount >= 20
  AND newestItemPubdate >= strftime('%s', '2026-01-01')
  AND (
        category1 IN ('technology', 'business')
        OR ((category1 IS NULL OR category1 = '') AND ({kw_filter}))
      )
"""
candidates = pd.read_sql(query, conn)
len(candidates)

38832

In [6]:
candidates["topic"] = candidates["category1"].replace("", "uncategorized (keyword match)")
candidates["subtopic"] = candidates["category2"].fillna("")
candidates.groupby(["topic", "subtopic"]).size().sort_values(ascending=False).head(20)

topic       subtopic
business    entrepreneurship    8293
                                7314
            investing           4310
            management          3056
            marketing           3018
            careers             2861
technology                      2681
business    non-profit          1336
            education           1082
technology  business             991
            news                 712
business    technology           564
            news                 541
technology  education            347
business    society              288
technology  science              177
business    health               171
technology  society              150
business    arts                 116
            government            87
dtype: int64

In [7]:
candidates["topic"].value_counts()                      # tech vs business vs uncategorized
candidates["episodeCount"].describe()                   # how big the shows are
candidates.groupby(["category1", "category2"]).size().sort_values(ascending=False).head(15)

category1   category2
business    entrepreneurship    8293
                                7314
            investing           4310
            management          3056
            marketing           3018
            careers             2861
technology                      2681
business    non-profit          1336
            education           1082
technology  business             991
            news                 712
business    technology           564
            news                 541
technology  education            347
business    society              288
dtype: int64